import { useState } from 'react'
import { fetchRecommendation } from '../api'

interface Props {
  token: string
}

export function RecommendationsPanel({ token }: Props) {
  const [recommendation, setRecommendation] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleFetch() {
    setIsLoading(true)
    setError(null)
    try {
      const text = await fetchRecommendation(token)
      setRecommendation(text)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch recommendation')
    } finally {
      setIsLoading(false)
    }
  }

  // Render bullet points as individual lines if the AI used • format.
  const lines = recommendation
    ? recommendation.split('\n').filter((l) => l.trim().length > 0)
    : []

  return (
    <div className="flex flex-col gap-3 p-4 rounded-2xl border border-lp-200 bg-lp-100">
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div className="flex flex-col gap-0.5">
          <h2 className="text-sm font-semibold text-lp-700">AI Sleep Recommendations</h2>
          <p className="text-[10px] text-lp-400">
            Personalized based on your last 7 nights of sensor data
          </p>
        </div>

        <button
          onClick={() => void handleFetch()}
          disabled={isLoading}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-lp-500 hover:bg-lp-600 text-white text-xs font-semibold transition-colors disabled:opacity-50 shrink-0"
        >
          {isLoading ? (
            <>
              <svg className="w-3 h-3 animate-spin" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582M20 20v-5h-.581M5.635 19A9 9 0 1 0 4.582 9" />
              </svg>
              Analyzing…
            </>
          ) : (
            <>
              <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09Z" />
              </svg>
              {recommendation ? 'Refresh' : 'Get Recommendation'}
            </>
          )}
        </button>
      </div>

      {error && (
        <p className="text-xs text-rose-400 bg-rose-900/20 border border-rose-700/40 rounded-lg px-3 py-2">
          {error}
        </p>
      )}

      {!recommendation && !isLoading && !error && (
        <p className="text-xs text-lp-300 text-center py-4">
          Click above to get personalized tips based on your actual sensor readings.
        </p>
      )}

      {isLoading && (
        <div className="flex flex-col gap-2 py-2">
          <div className="h-3 bg-lp-100 rounded animate-pulse w-full" />
          <div className="h-3 bg-lp-100 rounded animate-pulse w-5/6" />
          <div className="h-3 bg-lp-100 rounded animate-pulse w-4/5" />
          <div className="h-3 bg-lp-100 rounded animate-pulse w-full" />
        </div>
      )}

      {recommendation && !isLoading && (
        <ul className="flex flex-col gap-2.5 pt-1">
          {lines.map((line, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-lp-800 leading-snug">
              <span className="text-lp-500 mt-0.5 shrink-0">
                {line.startsWith('•') ? '•' : '→'}
              </span>
              <span>{line.replace(/^[•→]\s*/, '')}</span>
            </li>
          ))}
        </ul>
      )}

      {recommendation && !isLoading && (
        <p className="text-[10px] text-lp-300 border-t border-lp-200 pt-2 mt-1">
          Generated by GPT-4o mini · Based on your real sensor history · Not medical advice
        </p>
      )}
    </div>
  )
}
